# This file was generated by GoReleaser. DO NOT EDIT.
cask "awstbx" do
  name "awstbx"
  desc "Unified CLI for AWS infrastructure automation"
  homepage "https://github.com/towardsthecloud/aws-toolbox"
  version "1.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awstbx"

  on_macos do
    on_intel do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_darwin_amd64.tar.gz"
      sha256 "98bcccee09f96e4f7483022d1039dc682b3046a375fbf1bec02dde61892b3563"
    end
    on_arm do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_darwin_arm64.tar.gz"
      sha256 "b2c370cd6ab4cc72332864eb3c7164c580e2fcda1680b7971fc25bac6ab122fa"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_linux_amd64.tar.gz"
      sha256 "f8095c905f847d08868a46985a839cfe729be50e9d498b0283c0776443111813"
    end
    on_arm do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_linux_arm64.tar.gz"
      sha256 "a1c964f8b566209bed5cd52e35b545f8c5e19ec069de3d19e1e6845446744d76"
    end
  end

  # No zap stanza required
end
