# This file was generated by GoReleaser. DO NOT EDIT.
cask "awstbx" do
  name "awstbx"
  desc "Unified CLI for AWS infrastructure automation"
  homepage "https://github.com/towardsthecloud/aws-toolbox"
  version "1.1.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awstbx"

  on_macos do
    on_intel do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_darwin_amd64.tar.gz"
      sha256 "c847b1358da662448c536578d2630353832e52938c615d0576eafaaf617363ca"
    end
    on_arm do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_darwin_arm64.tar.gz"
      sha256 "31dc2a63ba9e90671766b5eaf67fca1a4290a584746985a94149ba04065931dd"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_linux_amd64.tar.gz"
      sha256 "4bf919779cdbb29a06223f1bda52221d9a6abf31eb3d2d2a5718bf3afcea3d6e"
    end
    on_arm do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_linux_arm64.tar.gz"
      sha256 "5f66cde70e77bbfee88fc991b05c1628c3a578565fc8c1a5b579afa987c381e3"
    end
  end

  # No zap stanza required
end
