# This file was generated by GoReleaser. DO NOT EDIT.
cask "awstbx" do
  name "awstbx"
  desc "Unified CLI for AWS infrastructure automation"
  homepage "https://github.com/towardsthecloud/aws-toolbox"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "awstbx"

  on_macos do
    on_intel do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_darwin_amd64.tar.gz"
      sha256 "216beb1a8f4ae0e6b247f10007faff07e68c553144bd9d8229ed0e8c517ba4c0"
    end
    on_arm do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_darwin_arm64.tar.gz"
      sha256 "1a0b21c8c07f475d6473a400646f7c2677e5072301a77ea8151fc946b44d9cdf"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_linux_amd64.tar.gz"
      sha256 "03d7af2363d47a9ad07ceed31baba3b3f356b6982b9e9ee9bc3ab01833f63231"
    end
    on_arm do
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v#{version}/awstbx_#{version}_linux_arm64.tar.gz"
      sha256 "85fa1fd5b8bc89cb24e95b8fba1245b002e8b3b7d309ce766c6c49db30870635"
    end
  end

  # No zap stanza required
end
