# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Awstbx < Formula
  desc "Unified CLI for AWS infrastructure automation"
  homepage "https://github.com/towardsthecloud/aws-toolbox"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v0.0.1/awstbx_0.0.1_darwin_amd64.tar.gz"
      sha256 "f472f5c1bb9a9ff83d4eee789224580133bef9b70744af5521d5d58d3db06c79"

      define_method(:install) do
        bin.install "awstbx"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v0.0.1/awstbx_0.0.1_darwin_arm64.tar.gz"
      sha256 "3e2669fbfd105fd8894a41b36253915289f01c49e9558db142762a0408ba0cdb"

      define_method(:install) do
        bin.install "awstbx"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v0.0.1/awstbx_0.0.1_linux_amd64.tar.gz"
      sha256 "effd2fc765ea6626e373e8e150edd65ed1cb7e9e28cfb019b80de9f4dfbbc500"
      define_method(:install) do
        bin.install "awstbx"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/towardsthecloud/aws-toolbox/releases/download/v0.0.1/awstbx_0.0.1_linux_arm64.tar.gz"
      sha256 "2f93fada9c1ea16ab2d96d9a0d05265133301a8ec0ffd5f0063b65535c7dffb8"
      define_method(:install) do
        bin.install "awstbx"
      end
    end
  end
end
